# Generated by Django 3.2.6 on 2021-08-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Наименование'),
        ),
    ]
